services:
  db:
    image: mysql:8.0.40-debian
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3306:3306"
    expose:
      - '3306'
